config/routes.rb
Rails.application.routes.draw do
  resources :days


  resources :muscle_groups
  resources :workouts
  resources :weeks

  post 'weeks/add' => "weeks#add"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "weeks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :week
  has_many :workouts
end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
  belongs_to :workout
end

app/models/week.rb
class Week < ApplicationRecord
    has_many :days
    has_many :workouts, through: :days 

    validates :range, uniqueness: true 
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Turbo::Native
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    def index 
    end 

    def show
    end 

end

app/controllers/muscle_groups_controller.rb
class MuscleGroupsController < ApplicationController
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
    before_action :current_week, only: [:show, :edit, :update]

    def index
        @weeks = Week.all 
    end

    def new 
        @week = Week.new
    end 

    def add
        t = Date.today
        week = Week.new(range:t.all_week)
        
        if week.save
            days = t.all_week.to_a.map {|day| Day.create(day: day.strftime("%A %d"), week_id: week.id)} #each day needs to be an  actual dateobject
           redirect_to root_path, notice: "Created!"
        else 
            flash[:notice] = "Wait till next week!"
        end 
    end 

    def show 
    end 

    def update
        @week.update(week_params)

        redirect_to week_path(@week), notice: "Updated"
    end 

    def destroy 
    end 

    private 

    def current_week
        @week = Week.find(params[:id]) 
    end 
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/muscle_groups_helper.rb
module MuscleGroupsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeeklyVolumeTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weeks/index.erb
<div>
    <h1>Weeks!</h1>
    <%= flash[:notice] %>
    <%= button_to "Start New Week", weeks_add_path   %>
    <% @weeks.each do |week|%>
    <%= week.range %>
    <table>
        
        <tr>
            <% week.days.each do |day|%>
            <th><%=day.day%></th>
            <%end%>
            <th>Total Volume</th>
        </tr>
        <tr>
            <% week.days.each do |day|%>
            <th>Add your workout!</th>
            <%end%>
            <th>Total Volume</th>
        </tr>
    </table>
    <%end%>

</div>